apiVersion: v1
kind: Service
metadata:
  name: grafana-web
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30901
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
#    prometheus=prometheus-kube-prometheus-prometheus
#    prometheus: prometheus
    app.kubernetes.io/name: grafana

