apiVersion: v1
kind: Service
metadata:
  name: nginx-server-status-4promet
  labels:
    operated-prometheus: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  type: NodePort
  selector:
    app: nginx-server-4promet
  ports:
    - name: http
      port: 80
      nodePort: 30900
    - name: nginx-exporter
      port: 9113
      nodePort: 30901