apiVersion: v1
kind: Service
metadata:
  name: prometheus-web
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
#    prometheus=prometheus-kube-prometheus-prometheus
#    prometheus: prometheus
    app.kubernetes.io/name: prometheus

