apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  namespace: monitoring
  annotations:
    meta.helm.sh/release-name: prometheus
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app: nginx-web-svc
  endpoints:
  - path: /metrics
    port: nginx-exp-port