repositories:
- name: chartmuseum
  url: https://chartmuseum.github.io/charts
- name: jetstack
  url: https://charts.jetstack.io
- name: harbor
  url: https://helm.goharbor.io

helmDefaults:
  wait: true

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  values:
    - installCRDs: true

- name: chartmuseum
  needs:
    - cert-manager/cert-manager
  namespace: chartmuseum
  chart: chartmuseum/chartmuseum
  values:
    - ./chartmuseum/values.yaml

- name: harbor
  needs:
    - cert-manager/cert-manager
  namespace: harbor
  chart: harbor/harbor
  values:
    - ./harbor/values.yaml

apiVersions:
- v1
- v2
