apiVersion: v1
kind: Service
metadata:
  name: el-coordinating
  namespace: observability
spec:
  type: LoadBalancer
  ports:
  - name: web-api
    nodePort: 30903
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: coordinating-only
