apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        LogLevel     info
        Config_Watch On
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10


    [OUTPUT]
        Name            es
        Match           *
        Host            el-ingest
        Port            9200
        Logstash_Format On
        Logstash_Prefix fluent-bit
        Retry_Limit     False
        Suppress_Type_Name On

kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: bitnami-f
    meta.helm.sh/release-namespace: observability
  labels:
    app.kubernetes.io/instance: bitnami-f
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/part-of: fluent-bit
    app.kubernetes.io/version: 2.2.1
    helm.sh/chart: fluent-bit-0.6.5
    k8s-app: fluent-bit
  name: bitnami-f-fluent-bit-config
  namespace: observability
