apiVersion: v1
kind: Service
metadata:
  name: kibana-web-svc
  namespace: observability
spec:
  type: LoadBalancer
  ports:
  - name: web-svc
    nodePort: 30904
    port: 8080
    protocol: TCP
    targetPort: 5601
  selector:
#    app.kubernetes.io/name: elasticsearch
#    app.kubernetes.io/component: coordinating-only
    app: kibana
    app.kubernetes.io/instance: bitnami-k
