apiVersion: v1
kind: Service
metadata:
  name: loki-web
  namespace: loki
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30902
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
#    prometheus=prometheus-kube-prometheus-prometheus
#    prometheus: prometheus
    app.kubernetes.io/name: grafana-loki
    app.kubernetes.io/component: query-frontend

