grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana-web.monitoring
    path: /

  additionalDataSources:
    name: Loki
    type: Loki
    url: http://loki-web.loki:3100/
    access: direct
